[2024-11-18T01:37:25.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T01:37:25.626+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T01:37:18.253387+00:00 [queued]>
[2024-11-18T01:37:25.638+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T01:37:18.253387+00:00 [queued]>
[2024-11-18T01:37:25.639+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T01:37:25.667+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test> on 2024-11-18 01:37:18.253387+00:00
[2024-11-18T01:37:25.674+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T01:37:25.677+0000] {standard_task_runner.py:72} INFO - Started process 155 to run task
[2024-11-18T01:37:25.677+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'test', 'manual__2024-11-18T01:37:18.253387+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpuny8xip9']
[2024-11-18T01:37:25.679+0000] {standard_task_runner.py:105} INFO - Job 290: Subtask test
[2024-11-18T01:37:25.737+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.test manual__2024-11-18T01:37:18.253387+00:00 [running]> on host 4232cbe34102
[2024-11-18T01:37:25.848+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T01:37:18.253387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T01:37:18.253387+00:00'
[2024-11-18T01:37:25.850+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T01:37:25.851+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T01:37:25.851+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-11-18 01:37:25.627388+00:00
[2024-11-18T01:37:25.852+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T01:37:25.852+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T01:37:25.864+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T01:37:25.866+0000] {logging_mixin.py:190} INFO - Error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-18T01:37:25.866+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T01:37:25.879+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T01:37:25.880+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=test, run_id=manual__2024-11-18T01:37:18.253387+00:00, execution_date=20241118T013718, start_date=20241118T013725, end_date=20241118T013725
[2024-11-18T01:37:25.892+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T01:37:25.893+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T01:37:25.893+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 01:37:18.271278+00:00
[2024-11-18T01:37:25.894+0000] {logging_mixin.py:190} INFO - Task hostname:4232cbe34102 operator:PythonOperator
[2024-11-18T01:37:25.932+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T01:37:25.958+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-18T01:37:25.961+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
