[2024-11-18T20:30:16.907+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T20:30:16.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T20:20:00+00:00 [queued]>
[2024-11-18T20:30:17.031+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T20:20:00+00:00 [queued]>
[2024-11-18T20:30:17.032+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T20:30:17.106+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-18 20:20:00+00:00
[2024-11-18T20:30:17.117+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3769) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T20:30:17.121+0000] {standard_task_runner.py:72} INFO - Started process 3771 to run task
[2024-11-18T20:30:17.123+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'scheduled__2024-11-18T20:20:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/raw/__pycache__/fetch_data.py', '--cfg-path', '/tmp/tmps6m_8jl0']
[2024-11-18T20:30:17.126+0000] {standard_task_runner.py:105} INFO - Job 442: Subtask insert_sales_data
[2024-11-18T20:30:17.235+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T20:20:00+00:00 [running]> on host c06adc74012b
[2024-11-18T20:30:17.792+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-18T20:20:00+00:00'
[2024-11-18T20:30:17.794+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T20:30:17.795+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T20:30:17.795+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-18 20:30:17.011345+00:00
[2024-11-18T20:30:17.796+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T20:30:17.797+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T20:30:17.829+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T20:30:17.878+0000] {fetch_data.py:73} INFO - Sales data successfully inserted into PostgreSQL.
[2024-11-18T20:30:17.879+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T20:30:17.896+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T20:30:17.896+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=scheduled__2024-11-18T20:20:00+00:00, execution_date=20241118T202000, start_date=20241118T203017, end_date=20241118T203017
[2024-11-18T20:30:17.921+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T20:30:17.922+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T20:30:17.922+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 20:30:00.994707+00:00
[2024-11-18T20:30:17.923+0000] {logging_mixin.py:190} INFO - Task hostname:c06adc74012b operator:PythonOperator
[2024-11-18T20:30:17.982+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T20:30:18.014+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T20:30:18.029+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
