[2024-11-18T16:20:19.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T16:20:19.284+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T16:10:00+00:00 [queued]>
[2024-11-18T16:20:19.301+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T16:10:00+00:00 [queued]>
[2024-11-18T16:20:19.302+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T16:20:19.333+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_sales_data> on 2024-11-18 16:10:00+00:00
[2024-11-18T16:20:19.343+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1661) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T16:20:19.347+0000] {standard_task_runner.py:72} INFO - Started process 1670 to run task
[2024-11-18T16:20:19.350+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'insert_sales_data', 'scheduled__2024-11-18T16:10:00+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpz9_79h_n']
[2024-11-18T16:20:19.353+0000] {standard_task_runner.py:105} INFO - Job 379: Subtask insert_sales_data
[2024-11-18T16:20:19.456+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.insert_sales_data scheduled__2024-11-18T16:10:00+00:00 [running]> on host c06adc74012b
[2024-11-18T16:20:20.012+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='insert_sales_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T16:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-18T16:10:00+00:00'
[2024-11-18T16:20:20.014+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T16:20:20.015+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T16:20:20.016+0000] {logging_mixin.py:190} INFO - Current task name:insert_sales_data state:running start_date:2024-11-18 16:20:19.285216+00:00
[2024-11-18T16:20:20.017+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T16:20:20.018+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T16:20:20.048+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T16:20:20.096+0000] {fetch_data.py:73} INFO - Sales data successfully inserted into PostgreSQL.
[2024-11-18T16:20:20.097+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T16:20:20.117+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T16:20:20.118+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=insert_sales_data, run_id=scheduled__2024-11-18T16:10:00+00:00, execution_date=20241118T161000, start_date=20241118T162019, end_date=20241118T162020
[2024-11-18T16:20:20.136+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T16:20:20.137+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T16:20:20.138+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 16:20:00.094149+00:00
[2024-11-18T16:20:20.139+0000] {logging_mixin.py:190} INFO - Task hostname:c06adc74012b operator:PythonOperator
[2024-11-18T16:20:20.167+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T16:20:20.197+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T16:20:20.201+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
