[2024-11-18T00:25:50.408+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T00:25:50.466+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T00:25:34.488720+00:00 [queued]>
[2024-11-18T00:25:50.489+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.test manual__2024-11-18T00:25:34.488720+00:00 [queued]>
[2024-11-18T00:25:50.490+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T00:25:50.536+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test> on 2024-11-18 00:25:34.488720+00:00
[2024-11-18T00:25:50.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=894) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T00:25:50.550+0000] {standard_task_runner.py:72} INFO - Started process 896 to run task
[2024-11-18T00:25:50.551+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'test', 'manual__2024-11-18T00:25:34.488720+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmppkht22ms']
[2024-11-18T00:25:50.554+0000] {standard_task_runner.py:105} INFO - Job 218: Subtask test
[2024-11-18T00:25:50.691+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.test manual__2024-11-18T00:25:34.488720+00:00 [running]> on host 32413fe3731c
[2024-11-18T00:25:51.813+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T00:25:34.488720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T00:25:34.488720+00:00'
[2024-11-18T00:25:51.816+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T00:25:51.819+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T00:25:51.821+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-11-18 00:25:50.467473+00:00
[2024-11-18T00:25:51.823+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2024-11-18T00:25:51.825+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T00:25:51.863+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-18T00:25:51.868+0000] {logging_mixin.py:190} INFO - Error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-18T00:25:51.870+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T00:25:51.917+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T00:25:51.920+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=test, run_id=manual__2024-11-18T00:25:34.488720+00:00, execution_date=20241118T002534, start_date=20241118T002550, end_date=20241118T002551
[2024-11-18T00:25:51.977+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T00:25:51.979+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T00:25:51.982+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2024-11-18 00:25:34.513555+00:00
[2024-11-18T00:25:51.986+0000] {logging_mixin.py:190} INFO - Task hostname:32413fe3731c operator:PythonOperator
[2024-11-18T00:25:52.056+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T00:25:52.168+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-18T00:25:52.177+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
